### ISSUE TITLE
asyncio support

### ISSUE THREAD

**Issue by awemulya** [pycasbin/databases-adapter#1]
This adapter is impressive when I used it in my project, do you have any plan to support asyncio support.
I wan to use  this adapter Asynchronously  with encode/database (https://github.com/encode/databases) handling the database actions.

**Comment by twinstar26** [comment]
Sure, I will tryout this weekend!

**Comment by awemulya** [comment]
Connect  database / database connection  using encode database
Implement/override adapters methods using async await. encode database operations.

we dont need `sqlalchemy-adapter` in any case.

**Comment by isasetiawan** [comment]
Hello there, I just try implement the adapter using encode databases. If you mind, you could check [this repo](https://github.com/sampingantech/databases-casbin-adapter)

**Comment by hsluoyz** [comment]
@isasetiawan thanks for this contribution! Added to the official docs: https://github.com/casbin/casbin-website/commit/071baa326177a1a58b462f0463063c1b7f334bf2

@awemulya plz use this one: https://github.com/sampingantech/databases-casbin-adapter

Closed here.
